trigger:
- master

pool:
  vmImage: 'windows-latest' # Tests require powershell

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'PowerShellClient.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'